defaults:
  run:
    working-directory: ./constraintlayout
env:
  DIST_DIR: /tmp/out/dist
  GRADLE_HOME: ${{ github.workspace }}/gradle-home
  OUT_DIR: /tmp/out
jobs:
  assemble:
    name: Assemble
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Cache gradle dependencies
      uses: actions/cache@v2
      with:
        key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
          hashFiles('**/*.gradle*') }}-${{ hashFiles('**/buildSrc/**') }}-${{ github.sha
          }}
        path: ${{ env.GRADLE_HOME }}/caches
        restore-keys: 'gradle-${{ hashFiles(''**/gradle/wrapper/gradle-wrapper.properties'')
          }}-${{ hashFiles(''**/*.gradle*'') }}-${{ hashFiles(''**/buildSrc/**'')
          }}-

          '
    - continue-on-error: true
      name: Clean gradle build cache to assemble fresh
      run: 'ls -lhrt "$GRADLE_HOME/caches" || true

        rm -rf "$GRADLE_HOME/caches/build-cache-1"

        ls -lhrt "$GRADLE_HOME/caches" || true

        '
    - continue-on-error: true
      name: Assemble with gradle
      run: ./gradlew assemble --build-cache --no-daemon --stacktrace --gradle-user-home
        "$GRADLE_HOME"
  compose-androidTest:
    name: Compose instrumentation tests
    needs: assemble
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Cache build artifacts
      uses: actions/cache@v2
      with:
        key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
          hashFiles('**/*.gradle*') }}-${{ hashFiles('**/buildSrc/**') }}-${{ github.sha
          }}
        path: ${{ env.GRADLE_HOME }}/caches
    - continue-on-error: true
      id: avd-cache
      name: AVD cache
      uses: actions/cache@v2
      with:
        key: avd-${{ matrix.api-level }}
        path: '~/.android/avd/*

          ~/.android/adb*

          '
    - continue-on-error: true
      if: steps.avd-cache.outputs.cache-hit != 'true'
      name: create AVD and generate snapshot for caching
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        disable-animations: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          -camera-back none
        force-avd-creation: false
        script: echo "Generated AVD snapshot for caching."
        target: google_apis
    - continue-on-error: true
      name: Compose Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        script: ./gradlew :compose:connectedCheck --build-cache --no-daemon --stacktrace
          --gradle-user-home "$GRADLE_HOME"
        target: google_apis
        working-directory: ./constraintlayout
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: instrumentation-test-results
        path: ${{ github.workspace }}/constraintlayout/compose/build/reports/androidTests/connected/**
    - continue-on-error: true
      if: ${{ always() }}
      name: Compose AndroidTest Report
      uses: mikepenz/action-junit-report@v2.9.0
      with:
        report_paths: ${{ github.workspace }}/constraintlayout/compose/build/outputs/androidTest-results/connected/TEST-*.xml
    strategy:
      matrix:
        api-level:
        - 30
  lint:
    name: Lint
    needs: assemble
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Cache build artifacts
      uses: actions/cache@v2
      with:
        key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
          hashFiles('**/*.gradle*') }}-${{ hashFiles('**/buildSrc/**') }}-${{ github.sha
          }}
        path: ${{ env.GRADLE_HOME }}/caches
    - continue-on-error: true
      name: Run tests
      run: ./gradlew lint --build-cache --no-daemon --stacktrace --gradle-user-home
        "$GRADLE_HOME"
  test:
    name: Unit Tests
    needs: assemble
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Cache build artifacts
      uses: actions/cache@v2
      with:
        key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
          hashFiles('**/*.gradle*') }}-${{ hashFiles('**/buildSrc/**') }}-${{ github.sha
          }}
        path: ${{ env.GRADLE_HOME }}/caches
    - continue-on-error: true
      name: Run tests
      run: ./gradlew test --build-cache --no-daemon --stacktrace --gradle-user-home
        "$GRADLE_HOME"
    - continue-on-error: true
      if: ${{ always() }}
      name: Core Test Report
      uses: mikepenz/action-junit-report@v2.9.0
      with:
        report_paths: ${{ github.workspace }}/constraintlayout/core/build/test-results/test/TEST-*.xml
name: core
on:
  repository_dispatch:
    types: trigger-ga___core.yml
